Repository code-hike/codehike, pull requests merged in 2022-07, with the labels that each got.

#213 Add skipLanguages config
  packages/mdx/dev/files.ts
  packages/mdx/src/remark/code.ts
  packages/mdx/src/remark/config.ts
  packages/mdx/src/remark/steps.tsx
  packages/mdx/src/remark/transform.code.ts
  packages/mdx/src/remark/transform.section.ts
Labels: patch, release

#214 Add from annotation
  packages/mdx/dev/content/assets/foo.js
  packages/mdx/dev/content/assets/foo.py
  packages/mdx/dev/content/external.mdx
  packages/mdx/dev/files.ts
  packages/mdx/pages/[name].tsx
  packages/mdx/src/remark/code.ts
  packages/mdx/src/remark/comment-data.ts
  packages/mdx/src/remark/config.ts
  packages/mdx/src/remark/transform.ts
  playground/src/index.css
Labels: patch, release

#216 Better scrollbars
  packages/mdx/dev/content/test.mdx
  packages/mdx/src/mdx-client/code.tsx
  packages/mdx/src/smooth-code/code-tween.tsx
  packages/mdx/src/smooth-code/index.scss
  packages/mdx/src/smooth-code/smooth-container.tsx
  packages/mdx/src/smooth-code/use-dimensions.tsx
Labels: patch, release

#219 v0.6.2
  packages/mdx/dev/content/assets/foo.js
  packages/mdx/dev/content/assets/foo.py
  packages/mdx/dev/content/external.mdx
  packages/mdx/dev/content/test.mdx
  packages/mdx/dev/files.ts
  packages/mdx/pages/[name].tsx
  packages/mdx/src/mdx-client/code.tsx
  packages/mdx/src/mdx-client/scrollycoding.scss
  packages/mdx/src/mdx-client/scrollycoding.tsx
  packages/mdx/src/mdx-client/section.tsx
  packages/mdx/src/mdx-client/slideshow.tsx
  packages/mdx/src/mdx-client/spotlight.scss
  packages/mdx/src/mdx-client/spotlight.tsx
  packages/mdx/src/mini-editor/code-browser.tsx
  packages/mdx/src/remark/code.ts
  packages/mdx/src/remark/comment-data.ts
  packages/mdx/src/remark/config.ts
  packages/mdx/src/remark/steps.tsx
  packages/mdx/src/remark/transform.code.ts
  packages/mdx/src/remark/transform.section.ts
  packages/mdx/src/remark/transform.ts
  packages/mdx/src/smooth-code/code-tween.tsx
  packages/mdx/src/smooth-code/index.scss
  packages/mdx/src/smooth-code/smooth-container.tsx
  packages/mdx/src/smooth-code/use-dimensions.tsx
  playground/src/index.css
Labels: release

#221 Add previews in steps
  packages/mdx/dev/content/test.mdx
  packages/mdx/src/mdx-client/scrollycoding.tsx
  packages/mdx/src/mdx-client/slideshow.tsx
  packages/mdx/src/mdx-client/spotlight.tsx
  packages/mdx/src/mdx-client/steps.tsx
  packages/mdx/src/remark/steps.tsx
  packages/mdx/src/remark/transform.scrollycoding.ts
  packages/mdx/src/remark/transform.slideshow.ts
  packages/mdx/src/remark/transform.spotlight.ts
Labels: minor, release

#233 Set `longestLineRef` once
  packages/mdx/src/smooth-code/use-dimensions.tsx
Labels: patch, release

#235 v0.7.1
  packages/mdx/src/mini-editor/code-browser.scss
  packages/mdx/src/mini-editor/code-browser.tsx
  packages/mdx/src/smooth-code/use-dimensions.tsx
Labels: release

#241 Remove overscroll-behavior
  packages/mdx/src/smooth-code/index.scss
Labels: patch

#242 v0.7.2
  packages/mdx/src/smooth-code/index.scss
Labels: release

#245 feat(244): Allow Slideshow controls to autoFocus
  .gitignore
  packages/mdx/dev/content/slideshow-autofocus.mdx
  packages/mdx/src/mdx-client/slideshow.tsx
Labels: patch, release

#249 Fix typescript module resolution
  .gitignore
  packages/mdx/package.json
  packages/mdx/rollup.config.js
  packages/mdx/src/components.tsx
  packages/mdx/src/index.tsx
  packages/mdx/src/mdx-client/annotations.tsx
  packages/mdx/src/remark/transform.ts
Labels: patch, release

#248 feat(#246): Add onChange and initialSlideIndex props to CH.Slideshow
  packages/mdx/dev/content/slideshow-onchange.mdx
  packages/mdx/src/mdx-client/slideshow.tsx
Labels: patch, release
