Repository code-hike/codehike, pull requests merged in 2022-05, with the labels that each got.

#172 Copy button component
  packages/mdx/dev/content/comment-annotations.mdx
  packages/mdx/dev/content/copy-button.mdx
  packages/mdx/dev/files.ts
  packages/mdx/dev/layout.tsx
  packages/mdx/package.json
  packages/mdx/pages/[name].tsx
  packages/mdx/pages/compile.tsx
  packages/mdx/pages/evaluate.tsx
  packages/mdx/pages/styles.css
  packages/mdx/pages/themes.tsx
  packages/mdx/src/mdx-client/annotations.tsx
  packages/mdx/src/mdx-plugin/plugin.ts
  packages/mdx/src/mini-editor/editor-frame.tsx
  packages/mdx/src/mini-editor/editor-shift.tsx
  packages/mdx/src/mini-editor/editor-tween.tsx
  packages/mdx/src/smooth-code/code-tween.tsx
  packages/mdx/src/smooth-code/copy-button.tsx
  packages/mdx/src/utils/code.ts
  packages/mdx/src/utils/theme.ts
  yarn.lock
Labels: minor, release

#174 Better props support for mdx
  contributing.md
  packages/mdx/dev/content/passing-props.mdx
  packages/mdx/src/index.tsx
  packages/mdx/src/mdx-client/code.tsx
  packages/mdx/src/mdx-plugin/ch-usage.ts
  packages/mdx/src/mdx-plugin/editor.tsx
  packages/mdx/src/remark/__snapshots__/comment-data.test.ts.snap
  packages/mdx/src/remark/annotations.ts
  packages/mdx/src/remark/code-files-reducer.tsx
  packages/mdx/src/remark/code.ts
  packages/mdx/src/remark/comment-data.test.ts
  packages/mdx/src/remark/comment-data.ts
  packages/mdx/src/remark/config.ts
  packages/mdx/src/remark/links.tsx
  packages/mdx/src/remark/nodes.ts
  packages/mdx/src/remark/steps.tsx
  packages/mdx/src/remark/to-estree.ts
  packages/mdx/src/remark/transform.code.ts
  packages/mdx/src/remark/transform.inline-code.ts
  packages/mdx/src/remark/transform.preview.ts
  packages/mdx/src/remark/transform.scrollycoding.ts
  packages/mdx/src/remark/transform.section.ts
  packages/mdx/src/remark/transform.slideshow.ts
  packages/mdx/src/remark/transform.spotlight.ts
  packages/mdx/src/remark/transform.ts
  packages/mdx/src/remark/unist-utils.ts
Labels: enhancement, release

#175 v0.5
  contributing.md
  examples/contentlayer/.babelrc
  examples/contentlayer/.gitignore
  examples/contentlayer/README.md
  examples/contentlayer/contentlayer.config.js
  examples/contentlayer/next-env.d.ts
  examples/contentlayer/next.config.js
  examples/contentlayer/package.json
  examples/contentlayer/pages/_app.tsx
  examples/contentlayer/pages/index.tsx
  examples/contentlayer/pages/posts/[slug].tsx
  examples/contentlayer/posts/post-one.mdx
  examples/contentlayer/posts/post-two.mdx
  examples/contentlayer/tsconfig.json
  packages/mdx/dev/content/comment-annotations.mdx
  packages/mdx/dev/content/copy-button.mdx
  packages/mdx/dev/content/passing-props.mdx
  packages/mdx/dev/files.ts
  packages/mdx/dev/layout.tsx
  packages/mdx/next.config.js
  packages/mdx/package.json
  packages/mdx/pages/[name].tsx
  packages/mdx/pages/compile.tsx
  packages/mdx/pages/evaluate.tsx
  packages/mdx/pages/styles.css
  packages/mdx/pages/themes.tsx
  packages/mdx/src/index.tsx
  packages/mdx/src/mdx-client/annotations.tsx
  packages/mdx/src/mdx-client/code.tsx
  packages/mdx/src/mdx-plugin/ch-usage.ts
  packages/mdx/src/mdx-plugin/editor.tsx
  packages/mdx/src/mini-editor/editor-frame.tsx
  packages/mdx/src/mini-editor/editor-shift.tsx
  packages/mdx/src/mini-editor/editor-tween.tsx
  packages/mdx/src/remark/__snapshots__/comment-data.test.ts.snap
  packages/mdx/src/remark/annotations.ts
  packages/mdx/src/remark/code-files-reducer.tsx
  packages/mdx/src/remark/code.ts
  packages/mdx/src/remark/comment-data.test.ts
  packages/mdx/src/remark/comment-data.ts
  packages/mdx/src/remark/config.ts
  packages/mdx/src/remark/links.tsx
  packages/mdx/src/remark/nodes.ts
  packages/mdx/src/remark/steps.tsx
  packages/mdx/src/remark/to-estree.ts
  packages/mdx/src/remark/transform.code.ts
  packages/mdx/src/remark/transform.inline-code.ts
  packages/mdx/src/remark/transform.preview.ts
  packages/mdx/src/remark/transform.scrollycoding.ts
  packages/mdx/src/remark/transform.section.ts
  packages/mdx/src/remark/transform.slideshow.ts
  packages/mdx/src/remark/transform.spotlight.ts
  packages/mdx/src/remark/transform.ts
  packages/mdx/src/remark/unist-utils.ts
  packages/mdx/src/smooth-code/code-tween.tsx
  packages/mdx/src/smooth-code/copy-button.tsx
  packages/mdx/src/utils/code.ts
  packages/mdx/src/utils/theme.ts
  yarn.lock
Labels: release

#179 Hide tabs
  examples/contentlayer/README.md
  examples/contentlayer/posts/one.mdx
  examples/contentlayer/posts/post-one.mdx
  examples/contentlayer/posts/post-two.mdx
  examples/contentlayer/posts/two.mdx
  packages/mdx/dev/content/scrollycoding.mdx
  packages/mdx/dev/content/section.mdx
  packages/mdx/src/remark/code-files-reducer.tsx
  packages/mdx/src/remark/steps.tsx
  packages/mdx/src/remark/transform.inline-code.ts
Labels: enhancement, release

#181 Expand button
  packages/mdx/dev/content/expand.mdx
  packages/mdx/dev/content/scrollycoding.mdx
  packages/mdx/dev/files.ts
  packages/mdx/package.json
  packages/mdx/pages/code-browser.tsx
  packages/mdx/pages/themes.tsx
  packages/mdx/src/mdx-client/code.tsx
  packages/mdx/src/mdx-client/scrollycoding.tsx
  packages/mdx/src/mini-editor/code-browser.scss
  packages/mdx/src/mini-editor/code-browser.tsx
  packages/mdx/src/mini-editor/dialog.scss
  packages/mdx/src/mini-editor/editor-frame.tsx
  packages/mdx/src/mini-editor/editor-tween.tsx
  packages/mdx/src/mini-editor/expand-button.tsx
  packages/mdx/src/mini-editor/index.scss
  packages/mdx/src/remark/config.ts
  packages/mdx/src/smooth-code/code-tween.tsx
  packages/mdx/src/smooth-code/copy-button.tsx
  packages/mdx/src/smooth-code/index.scss
  packages/mdx/src/utils/theme.ts
  yarn.lock
Labels: patch, release

#182 v0.5.1
  examples/contentlayer/README.md
  examples/contentlayer/posts/one.mdx
  examples/contentlayer/posts/post-one.mdx
  examples/contentlayer/posts/post-two.mdx
  examples/contentlayer/posts/two.mdx
  packages/mdx/dev/content/expand.mdx
  packages/mdx/dev/content/scrollycoding.mdx
  packages/mdx/dev/content/section.mdx
  packages/mdx/dev/files.ts
  packages/mdx/package.json
  packages/mdx/pages/code-browser.tsx
  packages/mdx/pages/themes.tsx
  packages/mdx/src/mdx-client/code.tsx
  packages/mdx/src/mdx-client/scrollycoding.tsx
  packages/mdx/src/mini-editor/code-browser.scss
  packages/mdx/src/mini-editor/code-browser.tsx
  packages/mdx/src/mini-editor/dialog.scss
  packages/mdx/src/mini-editor/editor-frame.tsx
  packages/mdx/src/mini-editor/editor-tween.tsx
  packages/mdx/src/mini-editor/expand-button.tsx
  packages/mdx/src/mini-editor/index.scss
  packages/mdx/src/remark/code-files-reducer.tsx
  packages/mdx/src/remark/config.ts
  packages/mdx/src/remark/steps.tsx
  packages/mdx/src/remark/transform.inline-code.ts
  packages/mdx/src/smooth-code/code-tween.tsx
  packages/mdx/src/smooth-code/copy-button.tsx
  packages/mdx/src/smooth-code/index.scss
  packages/mdx/src/utils/theme.ts
  yarn.lock
Labels: patch, release

#183 Merge main
  CHANGELOG.md
  examples/bundle-test/package.json
  examples/contentlayer/package.json
  examples/docusaurus/package.json
  examples/mdx-bundler/package.json
  examples/next-mdx-remote/package.json
  examples/nextjs/package.json
  examples/nextra/package.json
  examples/remix/package.json
  examples/vite/package.json
  lerna.json
  packages/mdx/CHANGELOG.md
  packages/mdx/package.json
Labels: internal

#186 Modify output of dist folder to merge all .d.ts files
  packages/mdx/package.json
  packages/mdx/rollup.config.js
  packages/mdx/src/mdx-client/code.tsx
  packages/mdx/tsconfig.json
  yarn.lock
Labels: release, internal

#185 Playground
  package.json
  packages/mdx/src/remark/transform.preview.ts
  playground/.gitignore
  playground/index.html
  playground/package.json
  playground/src/app.jsx
  playground/src/editor.jsx
  playground/src/favicon-16x16.png
  playground/src/favicon-32x32.png
  playground/src/favicon.ico
  playground/src/favicon.svg
  playground/src/index.css
  playground/src/main.jsx
  playground/src/preview.jsx
  playground/vite.config.js
  yarn.lock
Labels: patch, release

#187 Better playground
  package.json
  packages/mdx/dev/content/markdown.mdx
  packages/mdx/package.json
  packages/mdx/src/highlighter/index.tsx
  playground/package.json
  playground/src/app.jsx
  playground/src/editor.jsx
  playground/src/hash.js
  playground/src/index.css
  playground/src/preview.jsx
  playground/src/resizer.css
  playground/src/themes.js
  yarn.lock
Labels: patch, release

#188 Fix rose pine themes
  packages/mdx/dev/files.ts
  packages/mdx/src/mini-editor/editor-frame.tsx
  packages/mdx/src/remark/comment-data.ts
  playground/src/app.jsx
Labels: patch, release
