Repository code-hike/codehike, pull requests merged in 2022-02, with the labels that each got.

#116 Better default styles
  packages/mdx/src/client/annotations.tsx
  packages/mdx/src/client/code.tsx
  packages/mdx/src/client/inline-code.tsx
  packages/mdx/src/client/preview.tsx
  packages/mdx/src/client/scrollycoding.scss
  packages/mdx/src/client/scrollycoding.tsx
  packages/mdx/src/client/slideshow.scss
  packages/mdx/src/client/slideshow.tsx
  packages/mdx/src/client/spotlight.scss
  packages/mdx/src/client/spotlight.tsx
  packages/mdx/src/components.tsx
  packages/mdx/src/index.scss
  packages/mdx/src/plugin.ts
  packages/mdx/src/plugin/inline-code.ts
  packages/mdx/src/plugin/preview.ts
  packages/mdx/src/plugin/unist-utils.ts
  packages/mini-browser/package.json
  packages/mini-browser/src/buttons.tsx
  packages/mini-browser/src/mini-browser-hike.tsx
  packages/mini-browser/src/title-bar.tsx
  packages/mini-editor/src/editor-frame.tsx
  packages/mini-editor/src/index.scss
  packages/mini-frame/package.json
  packages/mini-frame/src/index.scss
  packages/mini-frame/src/mini-frame.tsx
  packages/mini-terminal/src/mini-terminal-transition.tsx
  packages/playground/content/simple-code.mdx
  packages/playground/content/test.mdx
  packages/smooth-code/src/code-tween.tsx
  packages/utils/src/theme.ts
Labels: enhancement, release

#124 Fix firefox copypasting
  packages/smooth-code/src/code-spring.tsx
  packages/smooth-code/src/code-tween.tsx
Labels: bug, release

#126 Handle invalid language
  packages/highlighter/src/index.tsx
  packages/playground/content/simple-code.mdx
Labels: bug, release

#129 Add `color-scheme` CSS
  packages/mdx/package.json
  packages/script/package.json
  packages/smooth-code/src/code-tween.tsx
  packages/utils/src/theme.ts
  yarn.lock
Labels: dependencies, release

#134 Changes style property to fix 'Unsupported style property color-scheme'
  packages/smooth-code/src/code-tween.tsx
Labels: bug, release

#136 Reset some code styles
  packages/smooth-code/src/index.scss
Labels: enhancement, release

#137 Add autoImport setting
  packages/mdx/src/plugin.ts
Labels: enhancement, release
