Repository code-hike/codehike, pull requests merged in 2023-06, with the labels that each got.

#370 Refactor themes
  .gitignore
  examples/browser/index.html
  examples/bundle-test/next.config.js
  examples/contentlayer/contentlayer.config.js
  examples/docusaurus/docusaurus.config.js
  examples/gatsby/gatsby-config.js
  examples/mdx-bundler/src/posts.js
  examples/next-mdx-remote/pages/posts/[slug].js
  examples/nextjs/next.config.js
  examples/nextra/next.config.js
  examples/nextra/package.json
  examples/remix/remix.config.js
  examples/remix/yarn.lock
  examples/vite/vite.config.js
  packages/mdx/dev/content/scrollycoding-preview-jsx.mdx
  packages/mdx/dev/content/scrollycoding.mdx
  packages/mdx/dev/content/test.mdx
  packages/mdx/dev/files.ts
  packages/mdx/package.json
  packages/mdx/pages/code-browser.tsx
  packages/mdx/pages/styles.css
  packages/mdx/pages/themes.tsx
  packages/mdx/rollup.config.js
  packages/mdx/src/classer/index.tsx
  packages/mdx/src/index.scss
  packages/mdx/src/mdx-client/annotations.tsx
  packages/mdx/src/mdx-client/code.tsx
  packages/mdx/src/mdx-client/inline-code.tsx
  packages/mdx/src/mdx-client/preview.tsx
  packages/mdx/src/mdx-client/scrollycoding.tsx
  packages/mdx/src/mdx-client/slideshow.tsx
  packages/mdx/src/mdx-client/slots.tsx
  packages/mdx/src/mdx-client/spotlight.tsx
  packages/mdx/src/mini-browser/buttons.tsx
  packages/mdx/src/mini-browser/index.scss
  packages/mdx/src/mini-browser/mini-browser-hike.tsx
  packages/mdx/src/mini-browser/title-bar.tsx
  packages/mdx/src/mini-editor/code-browser.scss
  packages/mdx/src/mini-editor/code-browser.tsx
  packages/mdx/src/mini-editor/dialog.scss
  packages/mdx/src/mini-editor/editor-frame.tsx
  packages/mdx/src/mini-editor/editor-tween.tsx
  packages/mdx/src/mini-editor/expand-button.tsx
  packages/mdx/src/mini-editor/index.scss
  packages/mdx/src/mini-frame/mini-frame.tsx
  packages/mdx/src/mini-terminal/mini-terminal-transition.tsx
  packages/mdx/src/remark/config.ts
  packages/mdx/src/remark/nodes.ts
  packages/mdx/src/remark/transform.ts
  packages/mdx/src/smooth-code/annotations.tsx
  packages/mdx/src/smooth-code/code-tween.tsx
  packages/mdx/src/smooth-code/index.scss
  packages/mdx/src/smooth-code/partial-step-parser.ts
  packages/mdx/src/smooth-code/smooth-lines.tsx
  packages/mdx/src/utils/index.tsx
  packages/mdx/src/utils/theme.ts
  packages/mdx/tsconfig.json
  playground/src/preview.jsx
  playground/src/themes.js
  yarn.lock
Labels: minor, release

#373 Fix dimensions when code starts hidden
  packages/mdx/src/highlighter/index.tsx
  packages/mdx/src/smooth-code/code-tween.tsx
  packages/mdx/src/smooth-code/index.scss
  packages/mdx/src/smooth-code/use-dimensions.tsx
Labels: patch, release

#376 `from` annotation with line range
  packages/mdx/dev/content/assets/bar.js
  packages/mdx/dev/content/external.mdx
  packages/mdx/src/remark/code.ts
Labels: patch

#383 Add new release message
  package.json
Labels: patch, release

#393 add yaml support from "from" annotation
  packages/mdx/dev/content/assets/foo.yaml
  packages/mdx/dev/content/external.mdx
  packages/mdx/src/remark/comment-data.ts
Labels: patch, release
